spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cssmp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "1234qweR"

server:
  port: 6666

logging:
  file:
    path: /Users/liupeng/logs/cssmp
  level:
    com.sptan: debug

